USE [master]
GO

/****** Object:  Database [EconetProject]    Script Date: 28/4/2022 10:02:50 ******/
CREATE DATABASE [EconetProject]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EconetProject', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\EconetProject.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EconetProject_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\EconetProject_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EconetProject].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EconetProject] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EconetProject] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EconetProject] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EconetProject] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EconetProject] SET ARITHABORT OFF 
GO

ALTER DATABASE [EconetProject] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EconetProject] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EconetProject] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EconetProject] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EconetProject] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EconetProject] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EconetProject] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EconetProject] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EconetProject] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EconetProject] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EconetProject] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EconetProject] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EconetProject] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EconetProject] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EconetProject] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EconetProject] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EconetProject] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EconetProject] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [EconetProject] SET  MULTI_USER 
GO

ALTER DATABASE [EconetProject] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EconetProject] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EconetProject] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EconetProject] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [EconetProject] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EconetProject] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [EconetProject] SET QUERY_STORE = OFF
GO

ALTER DATABASE [EconetProject] SET  READ_WRITE 
GO


